### ISSUE TITLE
Supervised learning for neural time series

### ISSUE THREAD

**Issue by jasperhajonides** [OxfordCodeReviewNet/forum#10]
## Brief project description
Hello all, I'm a DPhil student in Experimental Psychology working with electrophysiological and neuroimaging data. For my research, I often use supervised and unsupervised learning techniques on time series data. To facilitate this process I wrote a function that incorporates a few different classifiers and sliding window method that incorporates temporal information into the classifier. Available here: https://github.com/jasperhajonides/Supervised_Learning_TB

**Objective:** I would like to publish this code along with my manuscript so I'd like it to be as efficient as possible!

## The code
**Language**: <indicate language here>
**Type**:
- [X] Script or collection of scripts
- [ ] Library
- [ ] Standalone software
- [ ] I have no idea

The code that I would like to have reviewed is a function in Python and counts 182 lines (incl. descriptions). 

## Code review format
I'd rather
- [ ] Meet in person
- [X] Meet remotely
- [ ] Other format: <Describe your format here>
- [ ] No preference

**Comment by abhidg** [comment]
Hi @jasperhajonides would be happy to take a look at this -- does Wednesday afternoon work?

**Comment by jasperhajonides** [comment]
That would be great Abhishek, I'm free that afternoon. 2 pm UK time?

**Comment by abhidg** [comment]
Works for me! I will be on Teams.
