### ISSUE TITLE
Subcalssing threading.Thread in Python

### ISSUE THREAD

**Issue by jtmbeta** [OxfordCodeReviewNet/forum#11]
[pupil.txt](https://github.com/OxfordCodeReviewNet/forum/files/5108340/pupil.txt)
## Brief project description
I'm developing software to integrate an eye tracker with a 10-primary light source. The overall system will be used for pupillometry, e.g. measuring the pupil constriction response to a brief flash of light. Getting timestamps into the pupil data stream at the moment when a light flashes is one of the challanges I have been working on. My solution involves subclassing threading.Thread and using the eye tracker's forward-facing camera to get the timestamp. It seems to work well, but these are my first Python classes and I'm concerned about 'gotchas', correct use of super() and class attributes, etc. I'd be very grateful if someone with a good understanding of Python classes could take a look at my code and provide some feedback!

Best wishes,
Joel

## The code
**Language**: Python
**Type**:
- [ ] Script or collection of scripts
- [x] Library
- [ ] Standalone software
- [ ] I have no idea

**Further details**: In particular, I'm interested in getting feedback on the LightStamper() class in my code. The rest is general code for interacting with the eye tracking device. Attached as pupil.txt at the top of this issue.

## Code review format
I'd rather
- [ ] Meet in person
- [x] Meet remotely
- [ ] Other format: <Describe your format here>
- [ ] No preference

**Comment by dnadlinger** [comment]
Hi Joel, would be happy to have a chat. When would work best for you?

**Comment by jtmbeta** [comment]
Hi David, thanks, that’s great! Are you able to manage a time on 3rd / 4th September or any day the following week?

**Comment by jtmbeta** [comment]
Hi David, most days in the next two weeks would suit me if you are still available?

**Comment by inglesp** [comment]
Hi Joel, if you're still looking for a reviewer, I could do an hour this afternoon.  Can you let me know by midday?  Otherwise, I could do any day next week apart from Monday.

**Comment by jtmbeta** [comment]
Hi Peter, yes, I’m still looking for a reviewer, and an hour this afternoon would work great. Any time.

**Comment by inglesp** [comment]
How's 2pm with Google Meet?  I'll put a link in here just beforehand.

**Comment by jtmbeta** [comment]
Perfect - see you at 2pm.

**Comment by inglesp** [comment]
Sorry, something's come up.  Can we do 1pm or 3pm?

**Comment by jtmbeta** [comment]
Sure, 1pm?

**Comment by inglesp** [comment]
Works for me.

**Comment by inglesp** [comment]
I'm in https://meet.google.com/rfa-tuqv-hvz

**Comment by dnadlinger** [comment]
Oh, apologies, I didn't mean to ignore this; I must have missed your comment among the many GitHub notifications I tend to get these days, sorry! (I wouldn't have minded a ping via an `@` mention or via email.) I take it you've gone through everything and this issue can be closed? Still happy to meet up virtually if there is something left you'd like to discuss!

**Comment by jtmbeta** [comment]
No problem - It’s my fault for posting just before taking annual leave! I may as well have waited until I returned. But I had great input from Peter today and am feeling confident about my code. So yes, fine to close the issue. Thanks so much!
