### ISSUE TITLE
JSPsych Project

### ISSUE THREAD

**Issue by mcvc968** [OxfordCodeReviewNet/forum#12]
## Brief project description
Briefly describe the context around your code: research topic, what is your code for, for how long you have been developing it.

## The code
**HTML and JS**: <indicate language here>
**Type**:
- [ x ] Script or collection of scripts
- [ ] Library
- [ ] Standalone software
- [ ] I have no idea

**Further details**: <briefly describe the code you'll like to get reviewed.>

## Code review format
I'd rather
- [ ] Meet in person
- [ x ] Meet remotely
- [ ] Other format: <Describe your format here>
- [ ] No preference

[Keyboard Version of Motor Task copy.TXT](https://github.com/OxfordCodeReviewNet/forum/files/5239614/Keyboard.Version.of.Motor.Task.copy.TXT)

[study 1 session 1 copy.TXT]
(https://github.com/OxfordCodeReviewNet/forum/files/5239656/study.1.session.1.copy.TXT)

**Comment by tlestang** [comment]
Hello, could you give some information about your project, and what you'd expect from a code review?

**Comment by mcvc968** [comment]
Hi, 

Thanks for your response. I am trying to code a serial reaction time task, where people have to press certain keys in response to certain sounds and a memory where I would simply present visual stimuli on the screen. 

I am hoping to get a fresh pair of eyes on it in terms of debugging. It currently will not run as intended and I am a programming novice so the feedback I receive from the chrome developer tool I have been using is not always clear to me.

**Comment by mcvc968** [comment]
sorry *memory task, not memory.

**Comment by tlestang** [comment]
I'm no javascript expert, but happy to have a look. Would you be available tthis thursday at 2?

**Comment by mcvc968** [comment]
That sounds great! Thank you so much! How do we get in touch?

**Comment by tlestang** [comment]
If you visit my GitHub profile (by clicking on my profile picture), you'll find my email. Just send me an email and we can arrange a meeting
