### ISSUE TITLE
Take advantage of previously calculated parameters and store the "trained" custom classes?

### ISSUE THREAD

**Issue by rodrigolece** [OxfordCodeReviewNet/forum#13]
## Brief project description
I'm writing a piece of software that takes a spatial network with nodes and edges (with the nodes are embedded in 2D space for example) and computes a new network where only the statistically relevant edges are kept. This relies on comparing the weights associated with each edge to, among other models, the [gravity model](https://en.wikipedia.org/wiki/Trip_distribution#Gravity_model).

To construct the model predictions, I compute the parameters of the model that best fit the data, and then I do an expensive calculation of a set of variables called balancing factors. Since these calculations are expensive, but I do not need to them often, I would like to store my "trained" model for later re-use.

The question that I need help with is how to best store this data. I have defined a class that holds not just the gravity model but the other models a well, and the methods for fitting the parameters are methods within the class. Conceptually, what's the best way to represent and store my trained models? (So I'm asking less whether we store the data as numpy arrays or we pickle things, rather how do I best rewrite my class or my methods so decide to load the things I've computed before)

## The code
**Language**: Python.
**Type**:
- [ ] Script or collection of scripts
- [x] Library
- [ ] Standalone software
- [ ] I have no idea

**Further details**: <briefly describe the code you'll like to get reviewed.>

## Code review format
I'd rather
- [ ] Meet in person
- [x] Meet remotely
- [ ] Other format: <Describe your format here>
- [ ] No preference

**Comment by tlestang** [comment]
Hi @rodrigolece ! This definitely sounds like an interesting problem, but I'm wondering if this is maybe too high level for a one hour code review. I'm happy to review this piece of code with you. If we can't come up with anything, I'd suggest you get in touch with the [Oxford Research Software Engineering group](https://www.rse.ox.ac.uk/). We (used to) organize [software surgeries](https://www.rse.ox.ac.uk/software-surgeries/) for which your issue would be a great fit. We're planning on starting them again in the coming weeks.

Are you free sometimes next week?

**Comment by rodrigolece** [comment]
Sure thing, we can see where we get to in an hour :) I'm free all days apart from Thursday so you tell me what works best for you :smiley:

**Comment by tlestang** [comment]
Are you free next Tuesday around 4? I can send you a jitsi meeting link shortly before that if that works for you

**Comment by rodrigolece** [comment]
Yep, Tuesday works. I take you'll send an email? Feel free to use my public email here on Github :)
