### ISSUE TITLE
Reshaping array Python

### ISSUE THREAD

**Issue by jasperhajonides** [OxfordCodeReviewNet/forum#14]
## Brief project description
Hi, I'm Jasper a 4th year DPhil student in Experimental Psychology and have been using Python for a couple of years now. 

I have a very short query about an (effectively) 15-line python function. This function reshapes an array based on an integer that is passed into the function. 

## The code
**Language**: <Python>
**Type**:
- [x] Script or collection of scripts
- [ ] Library
- [ ] Standalone software
- [ ] I have no idea

**Further details**: The function is terribly inefficient, I would be interested to optimise the computational complexity and would be generally interested how to approach these type of array manipulations in a better way. 

## Code review format
I'd rather
- [ ] Meet in person
- [x] Meet remotely
- [ ] Other format: <Describe your format here>
- [ ] No preference

**Comment by inakleinbottle** [comment]
I'd be happy to review your code

**Comment by jasperhajonides** [comment]
That would be great! When would suit you, I'm relatively flexible. Does Tuesday afternoon or Wendesday Morning work?

**Comment by inakleinbottle** [comment]
Tomorrow afternoon is probably fine, around 2pm? Wednesday is not good for me.

**Comment by jasperhajonides** [comment]
Sure 2pm works for me, I can send you a zoom link tomorrow?

**Comment by inakleinbottle** [comment]
yes that would be fine, or we can do teams if you prefer.

**Comment by jasperhajonides** [comment]
Maybe thats easier, if you can drop me a message around 2pm? Thanks!
Jasper Hajonides van der Meulen
