### ISSUE TITLE
Optimising a pair statistic in C++/Rcpp

### ISSUE THREAD

**Issue by t-pollington** [OxfordCodeReviewNet/forum#15]
## Brief project description
I compute the _tau statistic_ (a spatiotemporal clustering statistic) by doing explicit summation of all pairs i.e. _N*(N-1)_ pairs for _N_ cases and using cases' location and time of disease onset to determine if pairs are related or not. I've been developing this code for nearly 2 years and _think_ I can't squeeze any more speed ups out of it. Speed is important as applying it to 25,000 points takes ~40s and need to get 1,000 bootstrap samples out. It uses some `Rcpp` commands as the `C` script is called in by R where the preamble analysis is done.

## The code
**Language**: `C++` with `Rcpp` commands using `#include <Rcpp.h>`
**Type**:
- [X] Script or collection of scripts
- [ ] Library
- [ ] Standalone software
- [ ] I have no idea

**Further details**: 
Speedups so far...
The script calls in vector variables as opposed to one big matrix, for speed. 
Its variables use short, unsigned and char data types when possible to keep things close to the registry as possible. All `if()` statements in the inner loops have been replaced with boolean arithmetic.

But I need help please...
It's all in `C` as I have no clue about _OOP_ and the speed ups that `C++` could offer?  It's likely to be run on Windows PC so if you know how to enable vectorisation that may help speed up the double loops over cases e.g. I have had some success with setting the `g++` compiler flags to utilise `-O3` optimisation and `-mavx2`. I'm not expecting to use parallel technologies here, but rather at a level above in R, where things are embarassingly parallel per bootstrap sample. Also if you know of any generic compiler flags to turn on vectorisation etc or turn off some unnecessary compiler checks then I might be able to add them to the Build tools in _RStudio_ during Build & Install. 
I've got no idea about memory stacks and pretty novice re: pointers. But I wonder if understanding this could help optimise things further. Focussing on just _case 1 odds_ from `lines 1--93` would be sufficient.

## Code review format
I'd rather
- [ ] Meet in person
- [X] Meet remotely. Teams, Zoom or Skype fine by me. 
- [ ] Other format: <Describe your format here>
- [ ] No preference

## If you're curious...
The code is below. Parts have already been [published](https://www.sciencedirect.com/science/article/pii/S2211675320300324?via%3Dihub) so I don't mind it being public.

```c
// Credit: Inspired and amended from https://github.com/HopkinsIDD/IDSpatialStats/commit/2782d6dcc9ee4be9855b5e468ce789425b81d49a by @gilesjohnr @jlessler
// And then amended from earlier code for the tau odds estimator https://doi.org/10.5281/zenodo.4906452 that featured in doi:10.1016/j.spasta.2020.100438
// Author: @t-pollington
// Date: 11 Jun 2021
#include <cstdlib>
#include <iostream>
#include <Rcpp.h>
#define NTYPE unsigned short //fine if N<=65535
using namespace std;
using namespace Rcpp;
// [[Rcpp::export]]

NumericVector getTauDist(const NumericVector x, const NumericVector y, 
                     const NumericVector onset, 
                     const NumericVector infEnd, 
                     const NumericVector suscStart, 
                     const NumericVector suscEnd, const NumericVector r_low, 
                     const NumericVector r, const IntegerVector index, 
                     const IntegerVector importT1, const IntegerVector importT2,
                     const IntegerVector estimator)
{ 
  NTYPE i,j,k;
  float dist2 = 0;
  float r2 = 0;
  float r2_low = 0;
  unsigned long num_cnt = 0, denom_cnt = 0; // counters
  NTYPE r_size = r.size();
  NTYPE N = x.size();
  int *inds = INTEGER(index);
  NumericVector tau(r_size, NULL);
  bool check = 1;
  bool bstrapconflict = 0;
  bool temprelated = 0; 
  bool withindist = 0; // d1<=dij<d2
  if(*inds==-1){ // if index set to -1 then turn off bootstrapping checks 
    check = 0; 
  }
  NTYPE T1 = importT1[0];
  NTYPE T2 = importT2[0];
  NTYPE estimatortype = estimator[0];

  switch(estimatortype){
    case 1: // odds
      {
      //calc thetaInf(d1=0,d2=Inf)
      float thetaInf = 0;
      for (i=0;i<N;i++) {
        for (j=0;j<N;j++) {
          bstrapconflict = ((inds[i] == inds[j]) && check)||(i == j); 
          // no self-comparisons during bootstrapping
          temprelated = (onset[inds[j]-1]-onset[inds[i]-1] <= T2) && 
            (onset[inds[j]-1]-onset[inds[i]-1] >= T1); 
          num_cnt = num_cnt + (!bstrapconflict && temprelated);
          denom_cnt = denom_cnt + (!bstrapconflict && !temprelated);
        }
      }
      thetaInf = (float)num_cnt/denom_cnt;
      
      // calc theta(r2_low,r2)
      for (k=0;k<r_size;k++) {
        num_cnt = 0;
        denom_cnt = 0;
        r2 = r[k]*r[k]; // transform to squared dists to make sqrt() redundant
        r2_low = r_low[k]*r_low[k];
        
        for (i=0;i<N;i++) {
          for (j=0;j<N;j++) { 
            // calculate squared distance
            dist2 = (x[inds[i]-1] - x[inds[j]-1])*
              (x[inds[i]-1] - x[inds[j]-1]) + 
              (y[inds[i]-1] - y[inds[j]-1])*
              (y[inds[i]-1] - y[inds[j]-1]);
            withindist = ((dist2 >= r2_low) && (dist2 < r2));
            if (!withindist) continue;
            bstrapconflict = ((inds[i] == inds[j]) && check)||(i==j);
            temprelated = (onset[inds[j]-1]-onset[inds[i]-1] <= T2) && 
              (onset[inds[j]-1]-onset[inds[i]-1] >= T1);
            num_cnt = num_cnt + (!bstrapconflict && temprelated);
            denom_cnt = denom_cnt + (!bstrapconflict && !temprelated);
          }
        }
        tau[k] = (float)num_cnt/denom_cnt; // theta(r.min,r.max)
        tau[k] = (float)tau[k]/thetaInf;
      }
      break;
      }
      
    case 2: // prevalence
      {
      // calc piInf(d1=0,d2=Inf)
      float piInf = 0;
      for (i=0;i<N;i++) {
        for (j=0;j<N;j++) {
          bstrapconflict = ((inds[i] == inds[j]) && check)||(i == j);
          temprelated = (onset[inds[j]-1]-onset[inds[i]-1] <= T2) && 
            (onset[inds[j]-1]-onset[inds[i]-1] >= T1);
          num_cnt = num_cnt + (!bstrapconflict && temprelated);
          denom_cnt = denom_cnt + !bstrapconflict; // \forall z_{ij}
        }
      }
      piInf = (float)num_cnt/denom_cnt;
      
      // calc pi(r2_low,r2)
      for (k=0;k<r_size;k++) {
        num_cnt = 0;
        denom_cnt = 0;
        r2 = r[k]*r[k];
        r2_low = r_low[k]*r_low[k];
        
        for (i=0;i<N;i++) {
          for (j=0;j<N;j++) { 
            dist2 = (x[inds[i]-1] - x[inds[j]-1])*(x[inds[i]-1] - x[inds[j]-1])+
              (y[inds[i]-1] - y[inds[j]-1])*(y[inds[i]-1] - y[inds[j]-1]);
            withindist = ((dist2 >= r2_low) && (dist2 < r2));
            if (!withindist) continue;
            bstrapconflict = ((inds[i] == inds[j]) && check)||(i==j);
            temprelated = (onset[inds[j]-1]-onset[inds[i]-1] <= T2) && 
              (onset[inds[j]-1]-onset[inds[i]-1] >= T1);
            num_cnt = num_cnt + (!bstrapconflict && temprelated);
            denom_cnt = denom_cnt + (!bstrapconflict);
          }
        }
        tau[k] = (float)num_cnt/denom_cnt; // pi(r.min,r.max)
        tau[k] = (float)tau[k]/piInf;
      }
      break;
      }
      
    case 3: // rate
      {
      // calc lambdaInf(d1=0,d2=Inf)
      float lambdaInf = 0;
      bool Z_ij = 0;
      NumericVector infStart = onset; // synonym
      for (i=0;i<N;i++) {
        for (j=0;j<N;j++) {
          bstrapconflict = ((inds[i] == inds[j]) && check)||(i == j);
          for (NTYPE t=504;t<612;t++) {
            Z_ij = (t>=infStart[i] && t<=infEnd[i]) && 
              (t>=suscStart[j] && t<=suscEnd[j]);
            denom_cnt = denom_cnt + (!bstrapconflict*Z_ij); 
          }
          // only sum over cases
          if (isnan(infStart[inds[i]-1]) || 
              isnan(infStart[inds[j]-1])) continue;
          temprelated = (infStart[inds[j]-1]-infStart[inds[i]-1] <= T2) && 
            (infStart[inds[j]-1]-infStart[inds[i]-1] >= T1);
          num_cnt = num_cnt + (!bstrapconflict && temprelated);
        }
      }
      lambdaInf = (float)num_cnt/denom_cnt;

      // calc lambda(r2_low,r2)
      for (k=0;k<r_size;k++) {
        num_cnt = 0;
        denom_cnt = 0;
        r2 = r[k]*r[k];
        r2_low = r_low[k]*r_low[k];

        for (i=0;i<N;i++) {
          for (j=0;j<N;j++) {
            dist2 = (x[inds[i]-1] - x[inds[j]-1])*(x[inds[i]-1] - x[inds[j]-1])+
              (y[inds[i]-1] - y[inds[j]-1])*(y[inds[i]-1] - y[inds[j]-1]);
            withindist = ((dist2 >= r2_low) && (dist2 < r2));
            if (!withindist) continue;
            bstrapconflict = ((inds[i] == inds[j]) && check)||(i==j);
            for (NTYPE t=504;t<612;t++) {
              Z_ij = (t>=infStart[i] && t<=infEnd[i]) && 
                (t>=suscStart[j] && t<=suscEnd[j]);
              denom_cnt = denom_cnt + (!bstrapconflict*Z_ij); 
            }
            // only sum over cases
            if (isnan(infStart[inds[i]-1]) || 
                isnan(infStart[inds[j]-1])) continue; 
            temprelated = (infStart[inds[j]-1]-infStart[inds[i]-1] <= T2) && 
              (infStart[inds[j]-1]-infStart[inds[i]-1] >= T1);
            num_cnt = num_cnt + (!bstrapconflict && temprelated);
          }
        }
        tau[k] = (float)num_cnt/denom_cnt; // lambda(r.min,r.max)
        tau[k] = (float)tau[k]/lambdaInf;
      }
        
      break;
      }    
    default:
      {
      return EXIT_FAILURE;
      }
  }  
  return tau;
}
```

**Comment by inakleinbottle** [comment]
Hi @t-pollington, I'd be happy to take a look at your code. A lot of my time is spent optimising numerical C/C++ code, so I might be of some use here.

To address your comment about C++ and OOP: moving to a C++ and/or OOP idiom will not _inherently_ improve performance of code.  I think any performance problems you're experiencing lie within the nested for loop. It looks, although I can't be sure, that the compiler will have some problem optimising this code because of the conditionals. Generally speaking, one should avoid conditional statements within a tight loop wherever possible.

You might be able to get some improvements by using OMP to parallelise this code. It does look like it would be a good candidate for that, since the loop body's are essentially independent. I'm not really an expert in this (yet) but I'm happy to help out.

Let me know what you think.

**Comment by t-pollington** [comment]
Hi @inakleinbottle that was a super speedy response, thanks! Would you be happy to meet or instead via comment snippet suggestions which I then trial out? I'm free to meet from tomorrow (Thursday) onwards.

**Comment by inakleinbottle** [comment]
I'm happy to meet via teams tomorrow afternoon?

**Comment by t-pollington** [comment]
Yes please, just sent you an invite to your @maths.ox.ac.uk email. Feel free to propose a better time if needs be.

**Comment by inakleinbottle** [comment]
@t-pollington I got it, thanks. The time works for me.

**Comment by tlestang** [comment]
Hi both, I'd be happy to join this one as well - it all sounds interesting! @t-pollington if that's okay with you could send me the invite as well? (`name.surname@cs.ox.ac.uk`)

**Comment by t-pollington** [comment]
More the merrier 😊

**Comment by dnadlinger** [comment]
I'll leave it to you all lest there will be too many cooks – it's easy for me to get nerd-sniped by problems like this, though. Some drive-by suggestions:

 - Split up the cases into separate functions, and benchmark/profile them individually. Will make code easier read, and possible the compiler optimiser more trigger-happy too.
 - Are there any chances for algorithmic speedups, or is the problem inherently O(N^2)?
 - If you are multi-threading at a higher level anyway, the biggest gain (apart from implementing the algorithm more optimally) will likely be from making sure the loops get auto-vectorised. There are some obvious stumbling blocks in the code as written, which I'm sure you can discuss tomorrow (what's with the 504/612 magic values by the way?), but I can recommend Clang's loop vectorizer diagnostics: https://llvm.org/docs/Vectorizers.html#diagnostics

**Comment by t-pollington** [comment]
Those are great @dnadlinger thanks. Some might be a bit restricted via the Rcpp interface in that profiling cpp in isolation may not be realistic Vs using Rprof but will see if that's possible. I'll add here what worked and what didn't for your interest.

**Comment by t-pollington** [comment]
By the way if readers of this aren't familiar with Rcpp basically it's running a cpp from within an R script. One adds a header to the cpp file and a few Rcpp specific functions for getting the data in and out of the C program but apart from that all C functionality is available.

**Comment by dnadlinger** [comment]
> Some might be a bit restricted via the Rcpp interface in that profiling cpp in isolation may not be realistic Vs using Rprof but will see if that's possible.

There are various levels of "performance optimisation" – if you are just interested in making the loop code itself as tight as possible, just using your own driver code instead of calling it from Rcpp should be quite representative (although I guess you could just profile the whole R executable, if you don't mind the extra noise from the R part).

**Comment by inakleinbottle** [comment]
@dnadlinger Your suggestion of splitting this into separate functions is a good idea, for readability and for reducing repeated code. It might be a little difficult to separate the logic from the R interface, given that data structures involved are specific to R; I don't know enough about the R `NumericVector` type at the moment to make sensible suggestions there. I'll have a look at the documentation before this afternoon.

Generally I've had the best experience with compile auto vectorisation when the tight loop is contained in a separate function by itself taking pointer-to-data arguments. This is especially true if the bounds can be given as template arguments, so the compiler knows the size at compile-time and it can do all the loop-unwinding that it wants.

**Comment by inakleinbottle** [comment]
Something that looks like this perhaps:
```
std::vector<double> new_x, new_y;
std::set unique_inds(index.begin(), index.end());
new_x.reserve(unique_inds.size());
new_y.reserve(unique_inds.size());

for (auto const& ind : unique_inds) {
    new_x.push_back(x[ind]);
    new_y.push_back(y[ind]);
}
```

**Comment by inakleinbottle** [comment]
As I suggested, you might also get some benefit from moving the computation of `dist2` into the first loop instead of recomputing it every time within the second loop. I propose the following:
```c++
    std::vector<double> dist2_mat;
    dist2_mat.reserve(x.size() * y.size());

    double thetaInf = 0, x_diff, y_diff;
    for (i=0;i<N;i++) {
        for (j=0;j<N;j++) {
            x_diff = x[inds[i] - 1] - x[inds[j] - 1];
            y_diff = y[inds[i] - 1] - y[inds[j] - 1];
            dist2_matrix.push_back(x_diff*x_diff + y_diff*y_diff);
            bstrapconflict = ((inds[i] == inds[j]) && check)||(i == j);
            // no self-comparisons during bootstrapping
            temprelated = (onset[inds[j]-1]-onset[inds[i]-1] <= T2) &&
                          (onset[inds[j]-1]-onset[inds[i]-1] >= T1);
            num_cnt = num_cnt + (!bstrapconflict && temprelated);
            denom_cnt = denom_cnt + (!bstrapconflict && !temprelated);
        }
    }
```
Then you can use a little lambda function (my favourite application of lambdas) to access the distance in the other matrix:
```c++
    auto get_dist = [&] (int i, int j) {
        return dist2_mat[i*x.size() + j];
    };

   for (k=0;k<r_size;k++) {
        std::cout << "Starting iteration: " << k <<  '\n';
        num_cnt = 0;
        denom_cnt = 0;
        r2 = r[k] * r[k]; // transform to squared dists to make sqrt() redundant
        r2_low = r_low[k] * r_low[k];

        for (i = 0; i < N; i++) {
            for (j = 0; j < N; j++) {
                 dist2 = get_dist(i, j);
...
            }
        }
```

**Comment by dnadlinger** [comment]
You might also want to look into inserting all points into a k-d tree first, which makes neighbour queries O(log N) on average. The total average time complexity should then be something like O(M N log N), where M is the average number of points within the distance cutoff. This, of course, only is an improvement if the data is sparse in the sense that most points don't lie within the `r` cutoff radius of most other points.

**Comment by t-pollington** [comment]
Thanks a lot for you time again @inakleinbottle & @tlestang 

So to summarise I'm going to implement the following step-by-step on the baseline code originally posted and report back on my findings!

We discussed the following:

- Other algorithms to the O(n^2) pairwise summation eg divide and conquer gridded methods with buffer method but pretty complex. Especially if maximum distance is small wrt spatial study region, though thetaInf still needs to be over everything.
- Symmetric treatment for distance calculation?
- Precompute distance matrix during thetaInf loop.
- Don't worry too much re cached data for access as CPU will prefetch. 
- Indexing R vs C
- To enable sequential memory access could sort x and y by indexes by row then columns. Remaining matrix area to sum over much reduced. See @inakleinbottle's code above
- Remove if() in inner loop but experiment if it's to stop a further nested loop.
- Precompute isnan()
- Using fns compiler can vectorise more easily. Can also profile code and check vectorising is working.
- float->double in cpp since Rcpp::NumericVector is double
- Need to check rcpp support for OMP and Clang
- Pointer to data args in tight loop with template args unnecessary as know size of data before runtime.

Thanks again guys!

**Comment by t-pollington** [comment]
> You might also want to look into inserting all points into a k-d tree first ... This, of course, only is an improvement if the data is sparse in the sense that most points don't lie within the `r` cutoff radius of most other points.

Thanks @dnadlinger, yes I'm going to have to look into it. I can't avoid 100% pairwise computation at all distances to compute thetaInf which runs from d=0 to d=Inf. However for theta(d1,d2) it is a possibility as I'm only looking to compute it up to d2=1km, whereas the data spans 12x12km.

**Comment by t-pollington** [comment]
> ... I think any performance problems you're experiencing lie within the nested for loop. It looks, although I can't be sure, that the compiler will have some problem optimising this code because of the conditionals. Generally speaking, one should avoid conditional statements within a tight loop wherever possible.
Hi @inakleinbottle some feedback on removing `if() continue;` within the for for loop and computing a boolean, leads to 3x slower code! I think this shows the importance to test. Probably if the `if() continue;` could only come later in the loop or there were less computations after it then your suggestion would probably have been faster.

**Comment by inakleinbottle** [comment]
@t-pollington I guess it depends how well the branch predictor in the CPU is working well here. It isn't a given that conditionals in a loop is a bad thing, it really depends on a lot of factors. If preprocessing to remove conditionals involves a lot of copying data then it's likely that just using the conditional will be faster. CPUs are weird, they rarely do things in exactly in the way you might expect from looking at the code.

**Comment by t-pollington** [comment]
> you might also get some benefit from moving the computation of dist2 into the first loop instead of recomputing it every time within the second loop

Unfortunately this one either never finishes or the following error is thrown `"cannot allocate vector of size 4.8 Gb"` due to double-looping over 25K points results in needing a large vector. Another one ticked off the list, still glad I tried it so thanks for the suggestion.

**Comment by t-pollington** [comment]
Got a 22% speedup by getting rid of that indexing in the C code using `inds[]` and pre-sorting my data before calling the function to ensure sequential memory access so that the double loop sequentially goes through `i` and `j`. Thanks for the suggestion @inakleinbottle
