### ISSUE TITLE
Simulation of general random processes

### ISSUE THREAD

**Issue by tlestang** [OxfordCodeReviewNet/forum#5]
## Brief project description
I'm currently involved in [stochrare](https://github.com/cbherbert/stochrare), a python library that provides tools to simulate and analyse stochastic process (understand dynamical process with a random component).

Over the past month I've been working on extending the part of the code that deals with the simulation of the processes. It amounts to a couple of classes within a single python module.

It's all fairly basic python, but it would help if the reviewer is (even only roughly) familiar with general concepts around simulation. if you're familiar with words like "discretisation", or "timestep", that's enough :)

## The code
**Language**: Python
**Type**: A couple of python classes

**Further details**: Particularly, there's one method that I struggled to implement and test. I still find the logic of it quite convoluted... It feels like I just spent too much time on it recently to have a clear picture in mind, so it  would really help if I could describe it to someone else!

**Comment by inglesp** [comment]
Hi @tlestang, I could find an hour one afternoon this week to talk this over with you.

I work at the [EBM DataLab](https://ebmdatalab.net/) on projects like [OpenPrescribing](https://github.com/ebmdatalab/openprescribing/)
 and [OpenSAFELY](https://github.com/opensafely/), and have some ideas for how to test the implementation of complex logic.

I haven't done any numerical simulation for fifteen years, but I can try to ask good questions!

**Comment by tlestang** [comment]
Hi @inglesp , that's great. Would tomorrow 2pm or 3pm work for you?

**Comment by inglesp** [comment]
Let's say 3pm.  Is Google Meet OK?  I'll send you a link by email.

Will you get the chance to send me any code to look over beforehand?

**Comment by tlestang** [comment]
That's ok. We'd have a look at some of the methods in [this python module](https://github.com/cbherbert/stochrare/blob/merge_diffusion1d.DiffusionProcess/stochrare/dynamics/diffusion.py). But I'm not expecting you to have a look beforehand, I'll walk you through it tomorrow.

**Comment by mjaquiery** [comment]
I'll also join this if that's okay with you, @inglesp @tlestang. 
I can make the 3pm (BST?) meeting and have some experience with Python and simulation.

**Comment by tlestang** [comment]
Great! See you then

**Comment by tlestang** [comment]
Yes, BST I guess :)

**Comment by inglesp** [comment]
Have sent invite links to the email addresses linked against your GH accounts.
