### ISSUE TITLE
OpenFOAM Library

### ISSUE THREAD

**Issue by T-Hickling** [OxfordCodeReviewNet/forum#6]
## Brief project description
I'm a DPhil student in the Engineering Dept. I'm pretty happy with C++, but I don't have any proper training, so it would be good to get some feedback.

The code is a small class to implement a radially varying pressure boundary condition in OpenFOAM (an open source computational fluid dynamics solver). The class is dynamically linked into OpenFOAM at runtime.

## The code
**Language**: C++
**Type**:
- [ ] Script or collection of scripts
- [x] Library
- [ ] Standalone software
- [ ] I have no idea

## Code review format
I'd rather
- [ ] Meet in person
- [x] Meet remotely
- [ ] Other format: <Describe your format here>
- [ ] No preference

**Comment by fcooper8472** [comment]
@thicko - sounds rad!

I could definitely take a look at it, maybe later in the week.  How's Thursday/Friday afternoon for you?

**Comment by T-Hickling** [comment]
@fcooper8472 Great! Thursday afternoon is good, let me know what time works for you.

I've been trying to figure out ways of testing this stuff (I'll be writing a bigger chunk of code for OF soon) so if you've got any ideas for that that would be great too.

**Comment by fcooper8472** [comment]
4pm?

**Comment by T-Hickling** [comment]
Sounds good, see you then!

**Comment by T-Hickling** [comment]
Cheers Fergus - that was a useful chat! For anyone interested, the main things we discussed were:

- Testing - the difficulties of unit testing this kind of code (with dependencies on quite a large code base) and strategies for regression testing it.

- Using github actions to automate the testing.

- Using `override ` instead of `virtual` for class member methods.

**Comment by T-Hickling** [comment]
The github repo for this is here:

https://github.com/thicko/rotEqTotalPressure

**Comment by tlestang** [comment]
Just reopening this issue so it serves as an example for now
