### ISSUE TITLE
UNIQO: machine learning for quantum optics

### ISSUE THREAD

**Issue by paolomolignini** [OxfordCodeReviewNet/forum#7]
## Brief project description
UNIQO is a collection of mainly python modules (and some accessory bash scripts) that implement machine learning tasks with artificial neural networks using the Keras library with TensorFlow backend. The code performs regression of various observables from data obtained from another software (MCTDH-X). The observables in the data describe the ground state of an ultracold quantum optical systems (at present bosonic atoms in a double well potential). The aim is to find a better/faster/more reliable way of calculating certain observables from others (e.g. correlation functions from single shot images), and also to find a way to obtain observables that could not be measured directly in an experiment with the same calibrated apparatus (e.g. correlation functions in momentum space from single shots in real space). We are also starting to implement hyperparameter optimization via the HpBandSter package.

## The code
**Language**:  mostly python modules and classes using numpy, matplotlib, and keras, with an additional jupyter notebook.
**Type**:
- [X] Script or collection of scripts
- [ ] Library
- [ ] Standalone software
- [ ] I have no idea

**Further details**: We would like to get the code reviewed in terms of readability, modularity, and efficiency. An example module and a workflow chart are attached. We have a total of 7 main python modules/classes and some accessory scripts.
[ModelTrainingAndValidation.py.zip](https://github.com/OxfordCodeReviewNet/forum/files/4832689/ModelTrainingAndValidation.py.zip)
[workflow.pdf](https://github.com/OxfordCodeReviewNet/forum/files/4832684/workflow.pdf)

## Code review format
I'd rather
- [ ] Meet in person
- [X] Meet remotely
- [ ] Other format: <Describe your format here>
- [ ] No preference

**Comment by tlestang** [comment]
Hi @paolomolignini , happy to have a look some day this week. I'm free tomorrow afternoon or thursday all day. Would tomorrow 4pm work?

**Comment by paolomolignini** [comment]
Hi @tlestang, thank you for answering! I'm free tomorrow at 4pm (BST I presume? I'm currently in Switzerland so it will be 5pm for me). What's the best way to work remotely?

**Comment by tlestang** [comment]
Perfect, that works for me. 

> What's the best way to work remotely?

Several options are listed [here](https://github.com/OxfordCodeReviewNet/forum/blob/master/remote.md). If you're comfortable using a command-line text editor (like vim or emacs), the easiest way to go is to use tmate. Another straightforward solution is to use VSCode LiveShare. If you're used to other graphical editors (Sublime, Atom...) we could use Floobits. It's also fairly straightforward to setup, but I'm happy to walk you through it if you'd like :)

**Comment by paolomolignini** [comment]
I can use basic editing in vim, so we can try with tmate.

**Comment by tlestang** [comment]
@paolomolignini I sent you an invite via MS Teams

**Comment by paolomolignini** [comment]
I received it and RSVP'd, thanks!

**Comment by paolomolignini** [comment]
Thanks a lot @tlestang for this code reviewing session! It was fun and very very helpful! :)

**Comment by tlestang** [comment]
Fun indeed! glad to hear that it was helpful, that's a good bonus :)
