### ISSUE TITLE
Tkinter GUI for Greek Mythology Network

### ISSUE THREAD

**Issue by NicoleEic** [OxfordCodeReviewNet/forum#8]
## Brief project description
I've programmed an interactive GUI that displays a network to visualize the relationships between figures of Greek mythology. The code is openly accessible at Github: https://github.com/NicoleEic/Brain_and_Code/tree/master/network

## The code
**Language**: Python
**Type**:
- [ X] Script or collection of scripts
- [ ] Library
- [ ] Standalone software
- [ ] I have no idea

In particular, I would like to get some feedback about the structure of the code and the GUI functions and the way I packaged the repository to make it accessible via Pip. 

## Code review format
I'd rather
- [ ] Meet in person
- [X ] Meet remotely
- [ ] Other format: <Describe your format here>
- [ ] No preference

Only remote possible at the moment, I think? In case this changed in the meantime, I'd be happy to meet in a park where we have wifi access.

**Comment by tlestang** [comment]
Hi @NicoleEic , that looks fun! I have some python experience but zero GUI knowledge, so I'd be happy to have a look :) Would you have an hour sometimes this week, say Wed at 16?

**Comment by tlestang** [comment]
We discussed on Slack and we plan to do the review on Friday 31/07 at 10. Anybody interested in reviewing welcome to join!
