### ISSUE TITLE
Forward Euler C++ implementation

### ISSUE THREAD

**Issue by fcooper8472** [OxfordCodeReviewNet/forum#9]
## Brief project description
I am writing a web app (the "algorithm zoo") that will help explain algorithms with innovative interactive visualisations and show people their implementations. Rather than presenting difficult-to-read pseudo-code, the app will show users an implementation of each algorithm in many different languages so they can read the implementation details in the language they understand best.

## The code
**Language**: C++
**Type**:
- [x] Script or collection of scripts
- [ ] Library
- [ ] Standalone software
- [ ] I have no idea

**Further details**: The first algorithm I am implementing is a straightforward Forward Euler scheme for solving ordinary differential equations.  I have a first draft for the implementation, but I would like to discuss with one or more people whether the implementation is good - where the goal is to make it as easy as possible to understand the algorithm - rather than for it to be an efficient/general implementation that might appear in a "real" C++ library.  My hope is that getting consensus on what makes an implementation easy to understand will then be more widely applicable to other languages and algorithms in the zoo.

## Code review format
I'd rather
- [ ] Meet in person
- [x] Meet remotely
- [ ] Other format
- [ ] No preference

**Comment by T-Hickling** [comment]
Hey @fcooper8472, I'm up for reviewing this is you're still looking for someone!

**Comment by dbrazel** [comment]
Hey Fergus, just following up here after our conversation on slack. My schedule is pretty open tomorrow or Wednesday afternoon, if either of those works for you.

**Comment by fcooper8472** [comment]
Hi @thicko & @dbrazel, sorry for dropping the ball on this!

Would tomorrow or any day next week work?

**Comment by dbrazel** [comment]
No problem, my schedule is fairly open tomorrow, how about 2pm?

**Comment by T-Hickling** [comment]
No worries @fcooper8472.

I'm pretty flexible tommorow too - 14:00 would work fine for me.

**Comment by fcooper8472** [comment]
Great, let's do 2pm then!

Teams OK?
